export const columns = [
  {
    name: "name",
    displayName: "Name",
    isSortable: true,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: true,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: "asc",
    columnId: "d2e69f2a-d71b-4e29-8f3d-149f5bcee752",
  },
  {
    name: "accountManager",
    displayName: "Account Manager",
    isSortable: false,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "28a8a331-e490-483d-b4e4-6f914febb807",
  },
  {
    name: "accountNumber",
    displayName: "Account Number",
    isSortable: true,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "eaf3746a-9871-417d-b31e-4d49cc553d2f",
  },
  {
    name: "address1",
    displayName: "Address",
    isSortable: true,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "66b5feb9-61dd-4cc2-b2d0-3e257c8c8c1b",
  },
  {
    name: "postCode",
    displayName: "Postcode",
    isSortable: true,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "d8713d2d-ac8f-46d6-9d3c-3ff93641aa12",
  },
  {
    name: "contact",
    displayName: "Contact Name",
    isSortable: false,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "939d5022-5697-4f19-8004-e38e869fce21",
  },
  {
    name: "telephone",
    displayName: "Telephone",
    isSortable: false,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "2f10e396-1fcf-4a49-a6eb-891f2d99f4ac",
  },
  {
    name: "emailAddress",
    displayName: "Email",
    isSortable: false,
    isSticky: false,
    isTooltip: null,
    isChangesDisabled: false,
    isRight: false,
    localResourceId: null,
    isShownMobile: true,
    isShownDesktop: true,
    orderBy: null,
    columnId: "252c43d2-6826-4120-99a4-c84042dcd167",
  },
];

export const mock_data = {
  AdditionalData: {
    Customers: [
      {
        Id: 2563475,
        Name: "Customer May",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "",
        Postcode: null,
        Contact: " ",
        EmailAddress: "customer@joblogic.com",
        Telephone: "0903891234",
        AccountNumber: 123456,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "Hello Manager",
        AccountManagerId: null,
      },
      {
        Id: 29281,
        Name: "Demo Customer",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "",
        Postcode: null,
        Contact: "Nhan customer 2",
        EmailAddress: "nhantr+customer2@joblogic.com",
        Telephone: "",
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 29263,
        Name: "Dien may cho lon ",
        Active: true,
        Address1: "Hai Ba Trung streey",
        Address2: null,
        Address3: "HCM",
        Address4: "VN",
        Address: "Hai Ba Trung streey, HCM, VN",
        Postcode: null,
        Contact: "Real 2 customer",
        EmailAddress: "khuongp@joblogic.com",
        Telephone: "",
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 2480113,
        Name: "DSD4 Amazon",
        Active: true,
        Address1: "5650 Kearny Mesa Road",
        Address2: "Kearny Mesa",
        Address3: "San Diego",
        Address4: "California",
        Address: "5650 Kearny Mesa Road, Kearny Mesa, San Diego, California",
        Postcode: "92111",
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 2480105,
        Name: "dsdsdsd",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "",
        Postcode: null,
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 28197,
        Name: "Green Feed",
        Active: true,
        Address1: "testing Address",
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "testing Address",
        Postcode: null,
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 2255645,
        Name: "Hayes, Kuhic and Treutel - Hobart",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "",
        Postcode: null,
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 28215,
        Name: "Lotte",
        Active: true,
        Address1: "Lotte address district 7",
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "Lotte address district 7",
        Postcode: null,
        Contact: "",
        EmailAddress: "",
        Telephone: "",
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 2255717,
        Name: "Lynch - Hilll - Kiara",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: null,
        Address4: null,
        Address: "",
        Postcode: null,
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
      {
        Id: 2485819,
        Name: "Monte Testaccio",
        Active: true,
        Address1: null,
        Address2: null,
        Address3: "Rome",
        Address4: "Metropolitan City of Rome Capital, Lazio",
        Address: "Rome, Metropolitan City of Rome Capital, Lazio",
        Postcode: "00153",
        Contact: " ",
        EmailAddress: null,
        Telephone: null,
        AccountNumber: null,
        CustomReference: null,
        CustomerTelephone: null,
        AccountManager: "",
        AccountManagerId: null,
      },
    ],
    BatchDeleteAllowed: false,
    HasBatchDeletePermission: true,
    PageSize: 10,
    PageIndex: 1,
    TotalCount: 22,
    PageSizeOptions: [
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "5 Results per page",
        Value: "5",
      },
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "10 Results per page",
        Value: "10",
      },
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "20 Results per page",
        Value: "20",
      },
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "30 Results per page",
        Value: "30",
      },
      {
        Disabled: false,
        Group: null,
        Selected: false,
        Text: "50 Results per page",
        Value: "50",
      },
    ],
  },
};

export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_PAGE_INDEX = 1;
export const CustomerOrderBy = {
  NAME_ASC: 0,
  NAME_DESC: 1,
  ADDRESS1_ASC: 2,
  ADDRESS1_DESC: 3,
  POSTCODE_ASC: 4,
  POSTCODE_DESC: 5,
  ACCOUNTNUMBER_ASC: 6,
  ACCOUNTNUMBER_DESC: 7,
};
